version: '3.8'


services:
  app:
    build: ./
    command:
      - ./e-commerce
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    restart: always
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5437:5432"